name: BreakPrevention
main: net.insxnity.breakprevention.BreakPrevention
load: STARTUP
version: 1.0
author: Insxnity
commands:
  bp:
  	description: BreakPrevention Core Command
    usage: /<command> reload
    alias: breakprevention
    