name: BreakPrevention
main: net.insxnity.breakprevention.BreakPrevention
version: 1.0
author: [Insxnity]
permissions:
  breakprevention.break:
    description: Allows a user to break blocks
    default: op
  breakprevention.place:
    description: Allows a user to place blocks
    default: op
  breakprevention.itemframe:
    description: Allows a user to interact with ItemFrames
    default: op